import { StyleSheet, Dimensions } from 'react-native';
import {
  Theme,
  screenSize as getScreenSize,
  PublicFont,
  PlatformUtils,
  CommonUtils,
  fontStore,
  FONT_MUTIPLE,
} from '@hw-vmall/vrn-basic-comp';
const width = Dimensions.get('window').width;
const size = getScreenSize(width);
const SCALE_SIZE = FONT_MUTIPLE.FONT_LEVEL_FOUR;
export default (theme: Theme) =>
  StyleSheet.create({
    containerPad: {
      backgroundColor: theme.S31.backgroundColor,
      marginLeft: size === 'small' ? 16 : 24,
      marginRight: size === 'small' ? 16 : 24,
      borderRadius: size === 'large' ? null : 16,
      marginTop: 12,
    },
    title: {
      ...(size === 'large' && { height: 64 }),
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'row',
      backgroundColor: theme.S31.backgroundColor,
      marginLeft: size === 'large' ? 24 : 12,
      marginRight: size === 'large' ? 24 : 12,
      marginTop: size === 'large' ? 12 : 0,
      paddingBottom: size === 'large' ? 0 : 8,
      paddingTop: size === 'large' ? 0 : 24,
    },
    titleLeft: {
      fontFamily: PublicFont.fontFamilyMedium,
      ...theme.C11,
      ...theme.T10,
      fontWeight: '700',
      fontSize: CommonUtils.getScaleSize(18, SCALE_SIZE),
      lineHeight: CommonUtils.getScaleSize(24, SCALE_SIZE),
      color: 'rgba(0,0,0,0.9)',
    },
    titleLeftWeb: {
      marginTop: 15,
      fontFamily: PlatformUtils.isIOS() ? null : 'HYQiHei-FES',
      ...theme.C11,
      ...theme.T13,
      fontWeight: '500',
    },
    titleRightScale: {
      marginTop: 0,
      textAlign: 'right',
      flexDirection: 'row',
      alignItems: 'center',
    },
    titleRight: {
      marginTop: size === 'large' ? 20 : 0,
      textAlign: 'right',
      flexDirection: 'row',
    },
    allScale: {
      marginRight: 4,
      fontFamily: PublicFont.fontFamilyMedium,
      ...theme.C13,
      ...theme.T7,
      fontSize: CommonUtils.getScaleSize(theme.T8.fontSize, SCALE_SIZE),
      lineHeight: CommonUtils.getScaleSize(19, SCALE_SIZE),
    },
    all: {
      marginTop: 2,
      marginRight: 4,
      fontFamily: PublicFont.fontFamilyMedium,
      ...theme.C13,
      ...theme.T7,
      lineHeight: 24,
    },
    svgStyle: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      display: 'flex',
      alignItems: 'flex-start',
      marginBottom: size === 'large' ? 24 : 16,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: size === 'large' ? 12 : null,
    },
    svgWidth: {
      width: size === 'medium' ? 48 : 36,
    },
    content: {
      marginTop: 4,
      textAlign: 'center',
      ...theme.C11,
      ...theme.T3,
      fontWeight: '400',
      fontSize: CommonUtils.getScaleSize(theme.T4.fontSize, SCALE_SIZE),
      lineHeight: CommonUtils.getScaleSize(theme.T4.lineHeight, SCALE_SIZE),
    },
    contentWeb: {
      marginTop: 10,
      fontFamily: PublicFont.fontFamilyMedium,
      textAlign: 'center',
      ...theme.C11,
      ...theme.T8,
      marginBottom: 8,
    },
    mark: {
      borderRadius: 16,
      backgroundColor: theme.C35.color,
      height: 16,
      paddingTop: 1,
      position: 'absolute',
      top: -3,
      left: size === 'large' ? 100 : 32,
      zIndex: 2,
    },
    evaluteGift: {
      borderRadius: 16,
      backgroundColor: theme.C35.color,
      height: 16,
      paddingTop: 1,
      position: 'absolute',
      top: -3,
      left: fontStore.fontMutiple > FONT_MUTIPLE.FONT_LEVEL_ONE ? 45 : 20,
      paddingHorizontal: 2,
      width: 52,
      zIndex: 1,
    },
    markText: {
      textAlign: 'center',
      ...theme.T1,
      ...theme.C17,
      fontFamily: PublicFont.fontFamilyMedium,
    },
    popUpWindow: {
      width: 458,
      height: 374,
      alignItems: 'center',
      position: 'absolute',
      zIndex: 333,
      backgroundColor: '#ffffff',
    },
    popUpWindowIcon: {
      paddingLeft: 430,
      height: 30,
      justifyContent: 'flex-end',
      paddingRight: 10,
    },
    popUpWindowImage: {
      width: 136,
      height: 136,
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 20,
    },
    popUpWindowText: {
      alignItems: 'center',
      marginBottom: 30,
    },
    popUpWindowHeight: {
      lineHeight: 21,
    },
    popUpWindowButton: {
      width: 170,
      height: 44,
      borderWidth: 1,
      alignItems: 'center',
      color: '#3a3a3a',
    },
    popUpWindowButtonText: {
      lineHeight: 44,
      fontSize: 18,
      margin: 'auto',
    },
    hide: {
      display: 'none',
    },
    page: {
      zIndex: 3,
    },
  });
